collections:
  - name: ansible.posix
    type: git
    source: https://github.com/ansible-collections/ansible.posix.git
    version: 1.5.4

  - name: community.docker
    type: git
    source: https://github.com/ansible-collections/community.docker.git
    version: 3.11.0

  - name: community.mysql
    type: git
    source: https://github.com/ansible-collections/community.mysql.git
    version: 3.9.0

  - name: community.crypto
    type: git
    source: https://github.com/ansible-collections/community.crypto.git
    version: 2.21.1

  - name: community.general
    type: git
    source: https://github.com/ansible-collections/community.general.git
    version: 9.2.0

  - name: devsec.hardening
    type: git
    source: https://github.com/dev-sec/ansible-collection-hardening.git
    version: 9.0.1
